const travel=[['an aisle seat','통로 좌석을'],['a window seat','창가 좌석을'],['my boarding pass','제 탑승권을'],['a seat upgrade','좌석 업그레이드를'],['a taxi to the hotel','호텔까지 가는 택시를'],['an early check-in','얼리 체크인을'],['a late check-out','레이트 체크아웃을'],['an extra towel','수건을 더'],['the Wi-Fi password','와이파이 비밀번호를'],['a room with a view','전망 좋은 방을'],['a city map','시내 지도를'],['directions to the station','역 가는 길을'],['a ticket for tomorrow','내일 표를'],['a table for two','2명 테이블을'],['the menu in English','영어 메뉴를'],['the bill, please','계산서를'],['a recommendation','추천을'],['a bottle of water','생수 한 병을'],['a charger','충전기를'],['a pharmacy nearby','근처 약국을'],['a doctor','의사를'],['a luggage storage service','짐 보관 서비스를'],['a refund','환불을'],['a different size','다른 사이즈를'],['a receipt','영수증을'],['a reservation','예약을'],['a tour guide','투어 가이드를'],['a rental car','렌터카를'],['a train schedule','기차 시간표를'],['help with my luggage','제 짐 관련 도움을']];
const business=[['the meeting agenda','회의 안건을'],['the presentation slides','발표 자료를'],['the project update','프로젝트 업데이트를'],['the latest report','최신 보고서를'],['a copy of the contract','계약서 사본을'],['the invoice','청구서를'],['the meeting link','회의 링크를'],['the deadline','마감일을'],['the budget details','예산 세부 사항을'],['feedback on this draft','이 초안에 대한 피드백을'],['a quick call','짧은 통화를'],['a follow-up meeting','후속 회의를'],['a calendar invite','캘린더 초대를'],['the client’s contact details','고객 연락처를'],['the final approval','최종 승인을'],['an extension','기한 연장을'],['a revised timeline','수정된 일정을'],['the next steps','다음 단계를'],['a status update','진행 상황 업데이트를'],['the meeting notes','회의록을'],['access to the folder','폴더 접근 권한을'],['the login details','로그인 정보를'],['the pricing information','가격 정보를'],['a quote','견적을'],['a signed copy','서명된 사본을'],['the delivery date','납기일을'],['a short introduction','짧은 소개를'],['a decision by Friday','금요일까지 결정을'],['more time to review this','검토할 시간을 더'],['help with this task','이 업무 관련 도움을']];
const forms=[['Could I get %s?','%k 받을 수 있을까요?','Could I get ~?','~을 받을 수 있을까요?'],['Is it possible to get %s?','%k 받을 수 있나요?','Is it possible to ~?','~하는 것이 가능한가요?'],['I’d like to request %s.','%k 요청하고 싶습니다.','I’d like to request ~.','~을 요청하고 싶습니다.'],['Do you have %s available?','%k 있나요?','available','이용 가능한'],['Can you help me with %s?','%k 도와주실 수 있나요?','help me with ~','~을 도와주다'],['May I have %s?','%k 받을 수 있을까요?','May I have ~?','~을 받을 수 있을까요?'],['I need %s, please.','%k 필요합니다.','I need ~.','~이 필요합니다.'],['Could you arrange %s?','%k 준비해 주실 수 있나요?','arrange','준비하다'],['Would you be able to provide %s?','%k 제공해 주실 수 있나요?','be able to','~할 수 있다'],['Can I ask for %s?','%k 요청해도 될까요?','ask for','요청하다']];
function make(topics,reply,replyTranslation){return topics.flatMap(([en,ko])=>forms.map(([s,k,e,ek])=>({sentence:s.replace('%s',en),translation:k.replace('%k',ko),reply,replyTranslation,expression:e,expressionTranslation:ek})))}
const courses={travel:{label:'여행',shortLabel:'TRAVEL',lessons:make(travel,'Of course. Let me check what’s available.','물론입니다. 가능한지 확인해 드릴게요.')},business:{label:'비즈니스',shortLabel:'BUSINESS',lessons:make(business,'Sure. I’ll send it over shortly.','네, 곧 보내드리겠습니다.')}};
const EPOCH='2026-08-30',KEY='daily-english-state';
function getLessonIndex(kstDate,length=300){const days=(Date.parse(`${kstDate}T00:00:00Z`)-Date.parse(`${EPOCH}T00:00:00Z`))/86400000;return((days%length)+length)%length}
function kst(){const p=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date());return Object.fromEntries(p.filter(x=>x.type!=='literal').map(x=>[x.type,x.value]))}function dateKey(){const p=kst();return`${p.year}-${p.month}-${p.day}`}
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));return s?.date===dateKey()&&courses[s.course]?s:{date:dateKey(),course:'travel',index:getLessonIndex(dateKey())}}catch{return{date:dateKey(),course:'travel',index:getLessonIndex(dateKey())}}}let state=load();function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function renderCourseTabs(){const box=document.getElementById('tabs');box.innerHTML='';Object.entries(courses).forEach(([id,c])=>{const b=document.createElement('button');b.className='tab';b.textContent=c.label;b.setAttribute('aria-selected',id===state.course);b.onclick=()=>{state={date:dateKey(),course:id,index:getLessonIndex(dateKey(),c.lessons.length)};render()};box.append(b)})}
function render(){if(state.date!==dateKey())state={date:dateKey(),course:state.course,index:getLessonIndex(dateKey(),courses[state.course].lessons.length)};const c=courses[state.course],l=c.lessons[state.index];document.getElementById('date').textContent=`${dateKey()} · KST`;document.getElementById('count').textContent=`${c.shortLabel} · ${String(state.index+1).padStart(3,'0')} / ${c.lessons.length}`;for(const[id,key]of[['sentence','sentence'],['translation','translation'],['reply','reply'],['reply-ko','replyTranslation'],['expression','expression'],['expression-ko','expressionTranslation']])document.getElementById(id).textContent=l[key];document.getElementById('progress').textContent=`${c.label} · ${state.index+1} / ${c.lessons.length}`;renderCourseTabs();fitAll();save()}
function scheduleNextLesson(){const p=kst(),ms=(+p.hour*3600 + +p.minute*60 + +p.second)*1000;setTimeout(()=>{render();scheduleNextLesson()},86400000-ms+500)}
const FIT=[['sentence-box','sentence'],['translation-box','translation'],['reply-box','reply'],['reply-ko-box','reply-ko']];
function overflows(box,el){return el.scrollHeight>box.clientHeight+1||el.scrollWidth>box.clientWidth+1}
function fit(box,el){let lo=8,hi=Math.min(box.clientHeight,200);el.style.fontSize=hi+'px';if(!overflows(box,el))return;while(hi-lo>.5){const mid=(lo+hi)/2;el.style.fontSize=mid+'px';overflows(box,el)?hi=mid:lo=mid}el.style.fontSize=lo+'px'}
function fitAll(){for(const[b,e]of FIT)fit(document.getElementById(b),document.getElementById(e))}
globalThis.dailyEnglish={courses,getLessonIndex};document.addEventListener('DOMContentLoaded',()=>{document.getElementById('next').onclick=()=>{state.index=(state.index+1)%courses[state.course].lessons.length;render()};render();scheduleNextLesson();addEventListener('resize',fitAll);document.fonts?.ready.then(fitAll)});
